# -*- coding: utf-8 -*-
"""madlibs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rnH4HsqoqAC8yT-RyQ-0jmFW-Jm0arhx

This project is going to show string concatenation. Suppose we want to say 'subscribe to ___' where the blank is some string variable. There are a couple of ways we can do this
"""

#print('subscribe to ' + youtuber)
#print('subscribe to {}'.format(youtuber))
#print(f'subscribe to {youtuber}')

adject = input('Adjective: ')
verb1 = input('Verb1: ')
verb2 = input('Verb2: ')
famous_person = input('Famous Person: ')

madlib = f'Today I learned how to write {adject} by {verb1} videos on Youtube \nafter {verb2} to the YouTuber known as {famous_person}'
print(madlib)